DROP DATAVERSE geo IF EXISTS;
CREATE DATAVERSE geo;

CREATE TYPE geo.worldType AS {auto_id:uuid };
CREATE DATASET geo.world(worldType)  PRIMARY KEY auto_id AUTOGENERATED;
LOAD DATASET geo.world USING localfs
        (("path"="127.0.0.1:localhost://D:\\UW Fall 2020\\CSE414\\HW6\\mondial.adm"),("format"="adm"));
 /* Edit the absolute path above to point to your copy of mondial.adm. */
 /* Use '\' instead of '/' in a path for Windows. e.g., C:\414\hw\geo\mondial.adm. */