DROP DATAVERSE geoindex IF EXISTS;
CREATE DATAVERSE geoindex;

``` create country ```
USE geoindex;
CREATE TYPE countryType AS OPEN {
    `-car_code`: string,
    `-area`: string,
    population: string
};
CREATE DATASET country(countryType)
   PRIMARY KEY `-car_code`;
CREATE INDEX countryID ON country(`-car_code`) TYPE BTREE;
LOAD DATASET country USING localfs
    (("path"="127.0.0.1:localhost://D:\\UW Fall 2020\\CSE414\\HW6\\country.adm"),("format"="adm"));

``` create mountain ```
USE geoindex;
CREATE TYPE mountainType AS OPEN{
	`-id`: string,
	`-country`: string,
	auto_id: uuid
};
CREATE DATASET mountain(mountainType)
    PRIMARY KEY auto_id AUTOGENERATED;
CREATE INDEX mountainID ON mountain(`-country`) TYPE KEYWORD;

LOAD DATASET mountain USING localfs 
(("path"="127.0.0.1:localhost://D:\\UW Fall 2020\\CSE414\\HW6\\mountain.adm"),("format"="adm"));

``` create sea ```
USE geoindex;
CREATE TYPE seaType AS OPEN{
	`-id`: string,
	`-country`: string,
	auto_id: uuid
};
CREATE DATASET sea(seaType)
    PRIMARY KEY auto_id AUTOGENERATED;
CREATE INDEX seaID ON sea(`-country`) TYPE KEYWORD;

LOAD DATASET sea USING localfs 
(("path"="127.0.0.1:localhost://D:\\UW Fall 2020\\CSE414\\HW6\\sea.adm"),("format"="adm"));
